import cv2
DISPLAY_ALL_SOURCE_CODE = False

DRAW_FILENAME_EXTENSION_LIST = ["py", "md"]
DIRECTORY_IGNORED = [".git", ".idea", "__pycache__", ".ipynb_checkpoints"]

FILE_COLOR = (125,0,0)
DIR_COLOR = (0xff,0xd4,0)
FILE_PACK_COLOR = (224,255,255)  # cyan


CELL_WIDTH = 200
CELL_HEIGHT = 300

UPPER_PADDING = int(CELL_HEIGHT/10)
LEFT_PADDING = int(CELL_WIDTH/10)

CELL_WIDTH_PADDING = int(CELL_WIDTH * 0.4)
CELL_HEIGHT_PADDING = int(CELL_HEIGHT * 0.2)

CELL_POSITION_WIDTH_COEFFICIENT = CELL_WIDTH + CELL_WIDTH_PADDING
CELL_POSITION_HEIGHT_COEFFICIENT = CELL_HEIGHT + CELL_HEIGHT_PADDING

CELL_TITLE_WIDTH = int(CELL_WIDTH)
CELL_TITLE_HEIGHT = int(CELL_HEIGHT*0.2)

CELL_TITLE_FONT = cv2.FONT_HERSHEY_COMPLEX
CELL_BODY_FONT = cv2.FONT_HERSHEY_SIMPLEX

CELL_TITLE_FONT_SIZE = CELL_WIDTH*0.003
CELL_BODY_FONT_SIZE = CELL_WIDTH*0.002

CELL_LINE_PADDING_X = int(CELL_WIDTH * 0)
CELL_LINE_PADDING_Y = int(CELL_TITLE_HEIGHT*0.5)

CELL_BODY_INTERVAL = int(CELL_BODY_FONT_SIZE * 50)

CELL_TITLE_UPPER_PADDING = int(CELL_HEIGHT * 0.1)
CELL_TITLE_LEFT_PADDING = int(CELL_WIDTH * 0.1)


CELL_BODY_UPPER_PADDING = int(CELL_HEIGHT * 0.1)
