import cv2
DISPLAY_ALL_SOURCE_CODE = False
DRAW_DENSE_MAP = False

DRAW_FILENAME_EXTENSION_LIST = ["py", "md"]
DIRECTORY_IGNORED = [".git", ".idea", "__pycache__", ".ipynb_checkpoints"]

FILE_COLOR = (125,0,0)
DIR_COLOR = (0xff,0xd4,0)
FILE_PACK_COLOR = (224,255,255)  # cyan


CELL_WIDTH = 200 # 가로 길이를 기준으로 비율을 정하자
CELL_STANDARD_HEIGHT = int(1.618*CELL_WIDTH)

WB_UPPER_PADDING = int(CELL_STANDARD_HEIGHT/10)  # white board 모서리 부분의 패딩
WB_LEFT_PADDING = int(CELL_WIDTH/10)

WB_WIDTH_BETWEEN_CELLS = int(CELL_WIDTH * 0.4)  # 셀과 셀 사이의 패딩
WB_HEIGHT_BETWEEN_CELLS = int(CELL_STANDARD_HEIGHT * 0.2)

"""
WB_CELLS_WIDTH_COEFFICIENT = CELL_WIDTH + CELL_BETWEEN_WIDTH_PADDING  # 셀 같은 지점 사이의 간격 계수
WB_CELLS_POSITION_HEIGHT_COEFFICIENT = CELL_STANDARD_HEIGHT + CELL_BETWEEN_HEIGHT_PADDING
"""

CELL_TITLE_WIDTH = int(CELL_WIDTH)
CELL_TITLE_HEIGHT = int(CELL_STANDARD_HEIGHT*0.2)

CELL_TITLE_FONT = cv2.FONT_HERSHEY_COMPLEX
CELL_BODY_FONT = cv2.FONT_HERSHEY_SIMPLEX

CELL_TITLE_FONT_SIZE = CELL_WIDTH*0.003
CELL_BODY_FONT_SIZE = CELL_WIDTH*0.002

CELL_LINE_PADDING_X = int(CELL_WIDTH * 0)
CELL_LINE_PADDING_Y = int(CELL_TITLE_HEIGHT*0.5)

CELL_BODY_INTERVAL = int(CELL_BODY_FONT_SIZE * 100+ CELL_BODY_)

CELL_TITLE_UPPER_PADDING = int(CELL_STANDARD_HEIGHT * 0.1)
CELL_TITLE_LEFT_PADDING = int(CELL_WIDTH * 0.1)

CELL_HEIGHT_BETWEEN_TEXTS = int(CELL_BODY_FONT_SIZE*30)

CELL_BODY_UPPER_PADDING = int(CELL_STANDARD_HEIGHT * 0.1)
CELL_BODY_INDENT = int(CELL_WIDTH*0.1)

CELL_BODY_UNDERLINE_PADDING = int(CELL_BODY_FONT_SIZE*20)