import cv2
DISPLAY_ALL_SOURCE_CODE = False
DRAW_DENSE_MAP = False

DRAW_FILENAME_EXTENSION_LIST = ["py", "md"]
DIRECTORY_IGNORED = [".git", ".idea", "__pycache__", ".ipynb_checkpoints"]

FILE_COLOR = (125,0,0)
DIR_COLOR = (0xff,0xd4,0)
FILE_PACK_COLOR = (224,255,255)  # cyan


CELL_WIDTH = 200 # 가로 길이를 기준으로 비율을 정하자
CELL_STANDARD_HEIGHT = int(1.618*CELL_WIDTH)

WB_UPPER_PADDING = int(CELL_STANDARD_HEIGHT/10)  # white board 모서리 부분의 패딩
WB_LEFT_PADDING = int(CELL_WIDTH/10)

WB_WIDTH_BETWEEN_CELLS = int(CELL_WIDTH * 0.4)  # 셀과 셀 사이의 수평간격
WB_HEIGHT_BETWEEN_CELLS = int(CELL_STANDARD_HEIGHT * 0.2)

"""
WB_CELLS_WIDTH_COEFFICIENT = CELL_WIDTH + CELL_BETWEEN_WIDTH_PADDING  # 셀 같은 지점 사이의 간격 계수
WB_CELLS_POSITION_HEIGHT_COEFFICIENT = CELL_STANDARD_HEIGHT + CELL_BETWEEN_HEIGHT_PADDING
"""

CELL_TITLE_WIDTH = int(CELL_WIDTH)  # 셀의 제목 가로길이
CELL_TITLE_HEIGHT = int(CELL_STANDARD_HEIGHT*0.2)  # 셀의 제목 세로 길이

CELL_TITLE_FONT = cv2.FONT_HERSHEY_COMPLEX  # 셀의 제목 글자 폰트
CELL_BODY_FONT = cv2.FONT_HERSHEY_SIMPLEX  # 셀의 본문 글자 폰트

CELL_TITLE_FONT_SIZE = CELL_WIDTH*0.003  # 셀의 제목 글자 크기
CELL_BODY_FONT_SIZE = CELL_WIDTH*0.002  # 셀의 본문 글자 크기

CELL_LINE_PADDING_X = int(CELL_WIDTH * 0)  # sx, sy로 부터 선의 시작까지의 거리
CELL_LINE_PADDING_Y = int(CELL_TITLE_HEIGHT*0.5)


CELL_BODY_HEIGHT_BETWEEN_TEXT = (CELL_BODY_FONT_SIZE*30)

CELL_TITLE_TEXT_UPPER_PADDING = int(CELL_STANDARD_HEIGHT * 0.1)  # sx,sy 로부터 title의 글자의 거리
CELL_TITLE_TEXT_LEFT_PADDING = int(CELL_WIDTH * 0.1)

CELL_HEIGHT_BETWEEN_BODY_TEXTS = int(CELL_BODY_FONT_SIZE*30)  # 본문 글자와 글자 사이의 거리

CELL_BODY_UPPER_PADDING = int(CELL_STANDARD_HEIGHT * 0.1)
CELL_BODY_LEFT_PADDING = int(CELL_WIDTH*0.1)

CELL_BODY_UNDERLINE_PADDING = int(CELL_BODY_FONT_SIZE*20)

CELL_BODY_TEXT_INTERVAL = int(CELL_BODY_FONT_SIZE * 100 + CELL_BODY_HEIGHT_BETWEEN_TEXT)